enabled_locales: ["en", "vi"]
name:
  maximum: 50
email:
  maximum: 255
pwd:
  minimum: 6
gravatar:
  size: 80
create:
  remember: 1
page: 10
expired:
  time: 2
micropost:
  content:
    maximum: 140
  picture:
    size: 5
  gravatar:
    size: 50
shared:
  userinfo:
    size: 50
views:
  micropost:
    accept: "image/jpeg,image/gif,image/png"
